name: Quiz Test Action

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  run-quiz-test:
    runs-on: windows-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: ▶️ Script ausführen (Command)
        env:
          CI: "true"
        run: |
          echo Starte Test...
          python Brainbuster.py
          echo Fertig!